name: automatic download to CodojoApp

on:
  workflow_dispatch:
    branches: [test]
jobs:
# Cancel Previous Redundant Builds
  download-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: keithweaver/aws-s3-github-action@v1.0.0 # Verifies the recursive flag
        name: sync folder
        with:
          command: sync
          source: s3://${{secrets.AWS_S3_BUCKET_APP}}/
          destination: ./public/app/
          aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws_region: ${{secrets.AWS_REGION}}
      - name: Commit changes
        run: |
         git config --local user.email "lautynievas09@gmail.com"
         git config --local user.name "Lautaro Nievas"
         git add .
         git diff-index --quiet HEAD || git commit -m "add app" -a
         git push origin main:main
