name: automatic download to CodojoApp

on:
  workflow_dispatch:
    branches: [test]
jobs:
# Cancel Previous Redundant Builds
  download-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: keithweaver/aws-s3-github-action@v1.0.0 # Verifies the recursive flag
        name: sync folder
        with:
          command: sync
          source: s3://${{secrets.AWS_S3_BUCKET_APP}}/
          destination: ./public/app/
          aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws_region: ${{secrets.AWS_REGION}}
      - name: Commit changes
        run: |
         git config --local user.email "lautynievas09@gmail.com"
         git config --local user.name "Lautaro Nievas"
         git pull origin dev-lautaro
         git add .
         git diff-index --quiet HEAD || git commit -m "add app" -a
         git push origin dev-lautaro:dev-lautaro

  build-app:
    needs: [download-app]
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout/@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/upload-artifact@v3
        with:
          name: app
          path: public/app/Codojo.jar

  update-app:
    needs: [build-app]
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout/@v3
        with:
          fetch-depth: 0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}
      - uses: actions/download-artifact@v3
        with:
          name: app
          path: app
      - name: Update S3 Bucket
        run: aws s3 sync --delete app s3://${{secrets.AWS_S3_BUCKET}}/app/
      - name: Invalidate the cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{secrets.AWS_DIST_ID}} \
            --paths "/*"