name: Codojo CI

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
# Cancel Previous Redundant Builds
  avoid_reduncy:
    runs-on: ubuntu-latest
    steps: 
      - name: Cancel Previus Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{github.token}}
# Lint settings
  lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout/@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Dependencies 
        run: npm ci
      - name: Lint
        run: npm run lint

#Configure security actions with snyk
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=low  

 # Creates a build and uploads an artifact
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout/@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Dependencies 
        run: npm ci
      - run: touch ./src/aws-exports.js
      - name: Build Static Website
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

# Test components
  e2e_test:
    needs: [lint,security, build]
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout/@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: touch ./src/aws-exports.js
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - name: E2E Test
        uses: cypress-io/github-action@v4
        env:
          CYPRESS_cognito_username: ${{secrets.CYPRESS_EMAIL_TEST}}
          CYPRESS_cognito_password: ${{secrets.CYPRESS_PASSWORD_TEST}}
          CYPRESS_googleClientId: ${{secrets.GOOGLE_CLIENT_ID}}
          CYPRESS_googleRefreshToken: ${{secrets.GOOGLE_REFRESH_TOKEN}}
          CYPRESS_googleClientSecret: ${{secrets.GOOGLE_CLIENT_SECRET}}
 # Deploy artifact to AWS
  deploy:
    needs: [e2e_test, build]
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout/@v3
        with:
          fetch-depth: 0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}
      - run: touch ./src/aws-exports.js
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - name: Deploy to S3 Bucket
        if: ${{ github.event_name == 'push' }}
        run: aws s3 sync --delete build s3://${{secrets.AWS_S3_BUCKET}}
      - name: Invalidate the cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{secrets.AWS_DIST_ID}} \
            --paths "/*"