name: Codojo CI

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:

  avoid_reduncy:
    runs-on: ubuntu-latest
    steps: 
      - name: Cancel Previus Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{github.token}}

  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout/@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Dependencies 
        run: npm ci
      - name: Build Static Website
        run: npm run build

  e2e_test:
    needs: [build]
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout/@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: E2E Test
        uses: cypress-io/github-action@v4
        env:
          CYPRESS_cognito_username: ${{secrets.CYPRESS_EMAIL_TEST}}
          CYPRESS_cognito_password: ${{secrets.CYPRESS_PASSWORD_TEST}}
    
  deploy:
    needs: [e2e_test]
    runs-on: ubuntu-latest
    env:
      DIST: build
    steps: 
      - name: Checkout
        uses: actions/checkout/@v3
        with:
          fetch-depth: 0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}
      - name: Deploy to S3 Bucket 
        run: aws s3 sync --delete ${{env.DIST}} s3://codojo-S3
      - name: Invalidate the cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{secrets.AWS_DIST_ID}} \
            --paths "/*"
          