name: Codojo CI

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DIST: build

    steps:
      - name: Cancel Previus Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{github.token}}
  
      - name: Checkout
        uses: actions/checkout/@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Install Dependencies 
        run: npm ci

      - name: Build Static Website
        run: npm run build

      - name: E2E Test
        uses: cypress-io/github-action@v4
        env:
          CYPRESS_cognito_username: ${{secrets.CYPRESS_EMAIL_TEST}}
          CYPRESS_cognito_password: ${{secrets.CYPRESS_PASSWORD_TEST}}

      - name: Deploy to S3 Bucket 
        if: ${{github.event_name == 'push'}}
        run: aws s3 sync --delete ${{env.DIST}} s3://${{secrets.AWS_S3_BUCKET}}

      - name: Invalidate the cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{secrets.AWS_DIST_ID}} \
            --paths "/*"
          